### ISSUE TITLE
Some tests needed

### ISSUE THREAD

**Issue by thamas** [gareth-fivemile/demo_umami#19]
"It has to be minimally automated tested to make sure that the profile doesn't spew errors when it's installed."

By Webchick at https://www.drupal.org/project/ideas/issues/2847582#comment-12393994

**Comment by thamas** [comment]
PR #18 fixes this!

**Comment by navneet0693** [comment]
@thamas Can this be closed then ?

**Comment by thamas** [comment]
I think so. :)
