### ISSUE TITLE
Preparation Time and Cooking Time Fields use 'suffix'

### ISSUE THREAD

**Issue by markconroy** [gareth-fivemile/demo_umami#30]
If we print the suffix on the 'Manage Display' page, then it's printed without a space, rendering something like this:
**Preparation Time: 20minutes**
When what we want is something like this:
**Preparation Time: 20 minutes**

I've edited the config to have a space before the suffix, but I have a feeling this might throw up some translations issues when people try to translate "minutes" instead of " minutes".

Should we leave it as is, or come up with something more elegant?
[the original bug was reported here](https://www.drupal.org/project/drupal/issues/2904243#comment-12407771)
P.S. I guess it would be nice if Drupal Core had a checkbox "add 1 space before suffix"

**Comment by gareth-fivemile** [comment]
We've discussed this - the example below the field shows ' m', plus this would be translated via config translation & not string translation.

**Comment by CaughtInTheBrambles** [comment]
This is the sort of issue you would resolve in css. for example you would want 120mph but not want 120 minutes so this is the sort of issue some custom css would resolve. Not sure how this sits with the theme project as you don't want css or sass code specific to a field to have this code in it.
