### ISSUE TITLE
Set URLs for our taxonomies?

### ISSUE THREAD

**Issue by markconroy** [gareth-fivemile/demo_umami#32]
Should we set urls for the categories we are creating? 

I think something like:
**http://umami-build.local/recipe-categories/snack**
looks a lot better than:
**http://umami-build.local/taxonomy/term/18**

If we also have listing pages for `/recipe-categories`, then we'd have decent looking breadcrumbs on those pages, as per bug report 6 here: https://www.drupal.org/project/drupal/issues/2904243#comment-12407771

**Comment by JayKandari** [comment]
@markconroy : Indeed! having a URL for terms will be good to read. 
We have 4 types of vocabularies, **Ingredients, Recipe category, Recipe cuisine, Tags**. 
IMO, we should follow this pattern of creating `{vocaublary}/{term_name}`. we should sluggify vocaublary and term_name to make it clean url. 

But, again we don't have taxonomy pages ready yet. 
Thanks !!
