### ISSUE TITLE
Some taxonomy terms have spaces at the start

### ISSUE THREAD

**Issue by gareth-fivemile** [gareth-fivemile/demo_umami#34]
e.g. ' North American'

This is because in the CSV, we have a comma separated list of tags - some of these have a space after the comma. When we are converting these terms for use in paths, they are set as '-north-american'.

Example from CSV: "Tapa,Vegetarian,Vegan,Latin American, Mexican, North American, Tex-Mex"

We should trim the tag either:
* Once we have exploded the tags to an array
i.e:
```
$tags = explode(',', $data['tags']);
foreach ($tags as $term) {
  $values['field_tags'][] = ['target_id' => trim($this->getTerm($term))];
}
```
* When trying to create the term:
```
protected function getTerm($term_name, $vocabulary_id = 'tags') {
  $term_name = trim($term_name);
  ...
}
```

I think option 2 might be better so we only have to do it once.

**Comment by JayKandari** [comment]
This is fixed !! Thanks 👍  Closing the issue.
