### ISSUE TITLE
Umami theme missing from admin/appearance?

### ISSUE THREAD

**Issue by owenmorrill** [gareth-fivemile/demo_umami#40]
When I install the profile either with a clone of this project or by the profile itself in a regular 8.5.x branch (adding the theme in as well), I don't actually see the Umami theme come up.

The theme seems to be working fine. It's just not showing up on admin/appearance.
![umami-theme-missing](https://user-images.githubusercontent.com/5008565/34740469-ba7aa104-f53c-11e7-9b03-fe34865efe6f.png)

**Comment by ckrina** [comment]
It is marked as internal so it's hidden in purpose. The reason is its goal is just to theme the content for the profile, at least for now.
