### ISSUE TITLE
Set site name during install

### ISSUE THREAD

**Issue by fuzzbomb** [gareth-fivemile/demo_umami#45]
The demo on platform.sh has "Site Install" as the site-name, which is what happens if you don't specify it with Drush.

Can we set the site name during install?  I suggest the full "Umami Food Magazine".

Site name is very important for accessibility.  The HTML `<title>` will be read out by a screen reader on page load, or when switching tabs and windows.

**Comment by gareth-fivemile** [comment]
Done:
https://github.com/gareth-fivemile/demo_umami/pull/53
