### ISSUE TITLE
Remove RSS Icons (at least for MVP)

### ISSUE THREAD

**Issue by markconroy** [gareth-fivemile/demo_umami#56]
The RSS icons on the taxonomy view and others is not in the designs, and looks a bit out of place.

Can someone remove them (maybe just disable that display in the view for now) and we can tackle them post MVP.

See https://github.com/lauriii/umami/issues/155

**Comment by fuzzbomb** [comment]
Would be good to keep feeds. They'll still be available as `<link>` in the HTML head?

Maybe we can introduce an RSS link to the site footer later on.

**Comment by markconroy** [comment]
@fuzzbomb 

I'd be happy to get these looking nice and working in about 2 weeks, so we'd have them for 8.5.0, but just not now for MVP on Monday.

**Comment by gareth-fivemile** [comment]
These have been disabled for now - will open another issue for re-implementing them post-MVP.

https://github.com/gareth-fivemile/demo_umami/commit/569d2e2a07ddf38a2fa1d9ae4ae7ee98127e66ae
